services:
  postgres:
    image: postgres
    ports:
      - '54320:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: saigon45 # Database name only — must match the db name in your .env POSTGRES_URL
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - .env
