export { Icon } from './Icon'
export type { IconProps } from './Icon'
export { iconOptions, iconRegistry } from './registry'
export type { IconDefinition, IconName } from './registry'
export { SocialIcon } from './SocialIcon'
export type { SocialIconProps } from './SocialIcon'
export { socialIconRegistry, socialPlatformOptions } from './socialIconRegistry'
export type { SocialIconDefinition, SocialPlatform } from './socialIconRegistry'
